# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nrjeit_development
  pool: 10
  username: root
  password: turtoise
  socket: /tmp/mysql.sock
  timeout: 2147483
  wait_timeout: 2147483
  flags: <%= 65536 | 131072 %>
  reconnect: true

test:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: nrjeit_test
    pool: 5
    username: root
    password: turtoise
    socket: /tmp/mysql.sock
    timeout: 10000
    reconnect: true

production:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: nrjeit_production
    pool: 5
    username: root
    password: turtoise
    socket: /tmp/mysql.sock
    timeout: 10000
    reconnect: true


development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
